"""empty message

Revision ID: 0be379784abd
Revises: 8a24ba36424c
Create Date: 2025-01-24 14:16:41.488045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be379784abd'
down_revision = '8a24ba36424c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('address_lat',
               existing_type=sa.NUMERIC(precision=9, scale=7),
               type_=sa.Numeric(precision=10, scale=7),
               existing_nullable=True)
        batch_op.alter_column('address_long',
               existing_type=sa.NUMERIC(precision=9, scale=7),
               type_=sa.Numeric(precision=10, scale=7),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('address_long',
               existing_type=sa.Numeric(precision=10, scale=7),
               type_=sa.NUMERIC(precision=9, scale=7),
               existing_nullable=True)
        batch_op.alter_column('address_lat',
               existing_type=sa.Numeric(precision=10, scale=7),
               type_=sa.NUMERIC(precision=9, scale=7),
               existing_nullable=True)

    # ### end Alembic commands ###
